<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TicketsTableSeeder extends Seeder
{
    public function run()
    {
        DB::table('tickets')->insert([
            [
                'id' => 76,
                'numero' => 'TICK-2025-000076',
                'titre' => 'sdfghjklmù',
                'description' => 'zezerzer',
                'demandeur_id' => 37,
                'assigne_a_id' => 1,
                'etat_id' => 2,
                'priorite_id' => 1,
                'type_ticket_id' => 2,
                'projet_id' => 2,
                'sla_id' => 1,
                'frequence_id' => 1,
                'date_echeance' => null,
                'date_premiere_reponse' => null,
                'date_resolution' => null,
                'temps_passe_minutes' => 0,
                'cout_estime' => null,
                'solution' => null,
                'champs_personnalises' => null,
                'created_at' => '2025-06-20 07:47:13',
                'updated_at' => '2025-06-20 07:47:13',
            ],
            [
                'id' => 77,
                'numero' => 'TICK-2025-000077',
                'titre' => 'sdfghjklmù',
                'description' => 'zezerzerazdzadazd',
                'demandeur_id' => 3,
                'assigne_a_id' => 1,
                'etat_id' => 2,
                'priorite_id' => 1,
                'type_ticket_id' => 2,
                'projet_id' => 2,
                'sla_id' => 1,
                'frequence_id' => 1,
                'date_echeance' => null,
                'date_premiere_reponse' => null,
                'date_resolution' => null,
                'temps_passe_minutes' => 0,
                'cout_estime' => null,
                'solution' => null,
                'champs_personnalises' => null,
                'created_at' => '2025-06-20 07:50:03',
                'updated_at' => '2025-06-26 10:43:22',
            ],
            [
                'id' => 78,
                'numero' => 'TICK-2025-000078',
                'titre' => 'sdfghjklmù',
                'description' => 'zezerzer',
                'demandeur_id' => 39,
                'assigne_a_id' => 1,
                'etat_id' => 2,
                'priorite_id' => 1,
                'type_ticket_id' => 2,
                'projet_id' => 2,
                'sla_id' => 1,
                'frequence_id' => 1,
                'date_echeance' => null,
                'date_premiere_reponse' => null,
                'date_resolution' => null,
                'temps_passe_minutes' => 0,
                'cout_estime' => null,
                'solution' => null,
                'champs_personnalises' => null,
                'created_at' => '2025-06-20 07:53:58',
                'updated_at' => '2025-06-20 07:53:58',
            ],
            [
                'id' => 80,
                'numero' => 'TICK-2025-000080',
                'titre' => 'ikkzae',
                'description' => 'hADtST3o0E',
                'demandeur_id' => 39,
                'assigne_a_id' => 1,
                'etat_id' => 3,
                'priorite_id' => 4,
                'type_ticket_id' => 2,
                'projet_id' => 2,
                'sla_id' => 2,
                'frequence_id' => 2,
                'date_echeance' => null,
                'date_premiere_reponse' => null,
                'date_resolution' => null,
                'temps_passe_minutes' => 0,
                'cout_estime' => null,
                'solution' => null,
                'champs_personnalises' => null,
                'created_at' => '2025-06-26 10:38:52',
                'updated_at' => '2025-06-26 10:38:52',
            ],
        ]);
    }
}